DEFINE TEMP-TABLE ttUserRole NO-UNDO
    BEFORE-TABLE bttUserRole
    FIELD UserRoleId AS CHARACTER FORMAT "x(36)"
    FIELD RoleTypeId AS CHARACTER FORMAT "x(36)"
    FIELD AppUserId AS CHARACTER FORMAT "x(36)"
    FIELD RentalCompanyId AS CHARACTER FORMAT "x(36)".
